#ifndef BITN_TOKEN_H
#define BITN_TOKEN_H

#include <stddef.h>

typedef enum {
    TOK_NUMBER, TOK_IDENTIFIER, TOK_STRING,
    TOK_FN, TOK_LET, TOK_MUT, TOK_RETURN, TOK_IF, TOK_ELSE, TOK_WHILE, TOK_FOR, TOK_IN,
    TOK_TRUE, TOK_FALSE,
    TOK_U8, TOK_U16, TOK_U32, TOK_U64, TOK_I8, TOK_I16, TOK_I32, TOK_I64, TOK_VOID,
    TOK_AND, TOK_OR, TOK_XOR, TOK_NOT, TOK_LSHIFT, TOK_RSHIFT, TOK_LROTATE, TOK_RROTATE,
    TOK_PLUS, TOK_MINUS, TOK_STAR, TOK_SLASH, TOK_PERCENT,
    TOK_EQ, TOK_NE, TOK_LT, TOK_GT, TOK_LE, TOK_GE,
    TOK_ASSIGN, TOK_PLUS_ASSIGN, TOK_MINUS_ASSIGN, TOK_AND_ASSIGN, TOK_OR_ASSIGN, TOK_XOR_ASSIGN,
    TOK_LPAREN, TOK_RPAREN, TOK_LBRACE, TOK_RBRACE, TOK_LBRACKET, TOK_RBRACKET,
    TOK_COLON, TOK_SEMICOLON, TOK_COMMA, TOK_DOT, TOK_ARROW, TOK_DARROW,
    TOK_EOF, TOK_ERROR,
} TokenType;

typedef struct {
    TokenType type;
    const char *value;
    int line;
    int column;
    int length;
} Token;

const char *token_type_name(TokenType type);
void token_print(Token *tok);

#endif
